async def ensure_indexes(db):
    await db.users.create_index("id", unique=True)
    await db.users.create_index("username", unique=True)
    await db.users.create_index("email")
    await db.planets.create_index("id", unique=True)
    await db.planets.create_index("owner_id")
    await db.planets.create_index([("position.x", 1), ("position.y", 1)])
    await db.fleets.create_index("id", unique=True)
    await db.fleets.create_index("user_id")
    await db.fleets.create_index([("position.x", 1), ("position.y", 1)])
    await db.fleets.create_index("movement_end_time")
    await db.ship_designs.create_index("id", unique=True)
    await db.ship_designs.create_index("user_id")
    await db.user_buildings.create_index("user_id", unique=True)
    await db.user_research.create_index("user_id", unique=True)
    await db.spaceport_ships.create_index("user_id")
    await db.invite_codes.create_index("code", unique=True)
    await db.battle_reports.create_index([("attacker_user_id", 1), ("created_at", -1)])
    await db.battle_reports.create_index([("defender_user_id", 1), ("created_at", -1)])
    await db.game_config.update_many({}, {"$unset": {"admin_password": ""}})